services:
  mysql-devops:
    image: mysql:8.4
    ports:
        - "3307:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=9GS)2£k:l1U`
        - MYSQL_DATABASE=devops

  gerenciador-tarefas:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=9GS)2£k:l1U`
      - MYSQL_DATABASE=devops